@url=http://localhost:4000/api
@writerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3NmM1MmVkNzUzYzllZmQ3YzU4ZGJiOSIsIm5hbWUiOiJNb2VleiBBbGkiLCJlbWFpbCI6Im1vZWV6YWxpMjM3NUBpY2xvdWQuY29tIiwiaXNWZXJpZmllZCI6ZmFsc2UsInJvbGUiOiJ3cml0ZXIifSwiaWF0IjoxNzM1MTUyMzY5LCJleHAiOjE3MzUyMzg3Njl9.dd0nqod1qxhjGBUrIOKkoWX7fkfp1UxggEoEKHM8OVQ
@readerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3NmM1MzQyNzUzYzllZmQ3YzU4ZGJjMiIsIm5hbWUiOiJNb2VleiBBbGkiLCJlbWFpbCI6Im1vZWV6YWxpMjM3NUBnbWFpbC5jb20iLCJpc1ZlcmlmaWVkIjpmYWxzZSwicm9sZSI6InJlYWRlciJ9LCJpYXQiOjE3MzUxNTI0NTIsImV4cCI6MTczNTIzODg1Mn0.Ld6yV9HVb6JRxjL3F6DiWdxpqbnPYzJO6Z7Re5NyBhs
###
GET {{url}}

###
POST {{url}}/writer
Content-Type:application/json

{
	"name":"Moeez Ali",
	"email":"moeezali2375@icloud.com",
	"password":"1234",
	"biography":"i am a rider",
	"role":"writer"
}

###
POST {{url}}/reader
Content-Type:application/json

{
	"name":"Moeez Ali",
	"email":"moeezali2375@gmail.com",
	"password":"1234",
	"role":"reader"
}

###
GET {{url}}/writer/verify/201861
Cookie: token={{writerToken}}

###
GET {{url}}/reader/verify/785581
Cookie: token={{readerToken}}

###
GET {{url}}/token
Cookie: token={{writerToken}}


###
POST {{url}}/login
Content-Type:application/json

{
	"email":"moeezali2375@gmail.com",
	"password":"1234"
}

###
POST {{url}}/logout
Cookie: token={{writerToken}}

###
GET {{url}}/genre
Cookie: token={{writerToken}}

###
GET {{url}}/writer
Cookie: token={{writerToken}}

###
PUT {{url}}/writer
Cookie: token={{writerToken}}
Content-Type: application/json

{
	"biography":"jutt dont care"
}

###
GET {{url}}/writer/book
Cookie: token={{writerToken}}

###
POST {{url}}/writer/book
Cookie: token={{writerToken}}
Content-Type: application/json

{
	"title":"School di kitaab 2",
	"description":"This is a test book 2",
	"content":"This is the content of a test book",
	"genreId":"671a17a2dee57c5b8d3aa99e"
}

###
PUT {{url}}/writer/book/67576d44267f155a200fc118
Cookie: token={{writerToken}}
Content-Type: application/json

{
	"genreId":"671a17a2dee57c5b8d3aa99e",
	"content":"Content Changed"
}

###
DELETE {{url}}/writer/book/6756bb9863054cfe5e5db1d5
Cookie: token={{writerToken}}


### READER

###
GET {{url}}/reader
Cookie: token={{readerToken}}

###
GET {{url}}/reader/book
Cookie: token={{readerToken}}

###
GET {{url}}/reader/book/676c53ae753c9efd7c58dbd9
Cookie: token={{readerToken}}

###
POST {{url}}/reader/book
Cookie: token={{readerToken}}
Content-Type: application/json

{
	"bookId":"676c53ae753c9efd7c58dbd9"
}

###
DELETE {{url}}/reader/book
Cookie: token={{readerToken}}
Content-Type: application/json

{
	"bookId":"67576550267f155a200fc0d4"
} 

### 
GET {{url}}/reader/writer/6759266ab5685aaa71948013
Cookie: token={{readerToken}}

###
POST {{url}}/reader/676c53ae753c9efd7c58dbd9/review
Cookie: token={{readerToken}}
Content-Type: application/json

{
  "star": 5,
  "description": "This is a another review."
}
